### ISSUE TITLE
Pertanyaan mengenai spek

### ISSUE THREAD

**Issue by girvinjunod** [williammfu/svd-image-compression#1]
> Program dapat menampilkan runtime program dan **persentase ukuran memori gambar yang dikompresi terhadap gambar original**

Halo kak, saya ingin bertanya mengenai spek di atas, yaitu bagian menampilkan persentase ukuran memori gambar. Ukuran memori gambar di sini yang dimaksud adalah ukuran gambar dari jumlah pixel atau ukuran memori dari file gambar ketika disimpan di PC ya kak?

(maksudnya seperti gambar ukuran 300x400, ukurannya apakah 300x400=120000 atau ukuran file ketika disimpan yang bisa jadi hanya 50000 saja)

**Comment by williammfu** [comment]
Ukuran memori dari file gambar saat disimpan ya (Misal: Image original dengan size 800kB berhasil dikompresi menjadi 640kB)
